## Using Open function

In [53]:
filename = 'data.txt'

In [11]:
file1 = open(filename,mode='r')

In [12]:
text_file1 = file1.read()

In [13]:
text_file1

'This is the most simplest file !!'

In [15]:
text_file1
file1.close()
file1.closed

True

In [ ]:
file = open('data.txt',mode='r')

In [2]:
file.read()

'This is the most simplest file !!'

In [3]:
file.read()

''

In [6]:
file.closed

True

In [5]:
file.close()

## With open function

In [32]:
filename

with open(filename,mode='r') as out_file:
    text = out_file.read()
text

'no it is a good file'

## Writing to the file

In [31]:
with open(filename,mode='w') as out_file:
    out_file.write('no it is a good file')

## Using pandas to load CSV

In [33]:
import pandas as pd

In [44]:
#pd.read_csv("Lending-company.csv")
csv_fileName = "Lending-company.csv"
csv_fileData = pd.read_csv(csv_fileName)

In [45]:
#type(pd.read_csv("Lending-company.csv"))
type(csv_fileData)
#print(csv_fileData)

pandas.core.frame.DataFrame

In [49]:
csv_fileData.columns

Index(['LoanID', 'StringID', 'Product', 'CustomerGender', 'Location', 'Region',
       'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
       'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
      dtype='object')

In [50]:
csv_fileData

LoanID     StringID    Product CustomerGender     Location    Region  \
0          1     LoanID_1  Product B         Female   Location 3  Region 2   
1          2     LoanID_2  Product D         Female   Location 6  Region 6   
2          3     LoanID_3  Product B           Male   Location 8  Region 3   
3          4     LoanID_4  Product A           Male  Location 26  Region 2   
4          5     LoanID_5  Product B         Female  Location 34  Region 3   
...      ...          ...        ...            ...          ...       ...   
1038    1039  LoanID_1039  Product B           Male  Location 73  Region 6   
1039    1040  LoanID_1040  Product A           Male  Location 82  Region 1   
1040    1041  LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1041    1042  LoanID_1042  Product B         Female  Location 26  Region 6   
1042    1043  LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0        17600.0  04/07/2018     2200         45          365       3221   
1            NaN  02/01/2019     2200         45          365       3161   
2        16600.0  08/12/2016     1000         45          365       2260   
3        17600.0         NaN     2200         45          365       3141   
4        21250.0  28/10/2017     2200         55          365       3570   
...          ...         ...      ...        ...          ...        ...   
1038     17300.0  29/12/2018     2200         45          365       3251   
1039         NaN  28/03/2018     2200         45          365       4090   
1040     17300.0  26/04/2018     2200         45          365       4051   
1041     16300.0  25/10/2016     1000         45          365       1930   
1042     17300.0  15/05/2019     2200         45          365       4451   

      AmtPaid60  AmtPaid360        LoanStatus  
0          4166       14621            Active  
1          4096       16041            Active  
2          3205       16340               NaN  
3          4166       16321            Active  
4          4745       14720            Active  
...         ...         ...               ...  
1038       4743       16617  Finished Payment  
1039       5582       16617  Finished Payment  
1040       5143       16617  Finished Payment  
1041       3462       15617  Finished Payment  
1042       4743       16617  Finished Payment  

[1043 rows x 15 columns]

## Importing data by changing default index column

In [55]:
csv_data_with_index = pd.read_csv(csv_fileName,index_col='LoanID')
csv_data_with_index

StringID    Product CustomerGender     Location    Region  \
LoanID                                                                 
1          LoanID_1  Product B         Female   Location 3  Region 2   
2          LoanID_2  Product D         Female   Location 6  Region 6   
3          LoanID_3  Product B           Male   Location 8  Region 3   
4          LoanID_4  Product A           Male  Location 26  Region 2   
5          LoanID_5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
1039    LoanID_1039  Product B           Male  Location 73  Region 6   
1040    LoanID_1040  Product A           Male  Location 82  Region 1   
1041    LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1042    LoanID_1042  Product B         Female  Location 26  Region 6   
1043    LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

        TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
LoanID                                                                       
1          17600.0  04/07/2018     2200         45          365       3221   
2              NaN  02/01/2019     2200         45          365       3161   
3          16600.0  08/12/2016     1000         45          365       2260   
4          17600.0         NaN     2200         45          365       3141   
5          21250.0  28/10/2017     2200         55          365       3570   
...            ...         ...      ...        ...          ...        ...   
1039       17300.0  29/12/2018     2200         45          365       3251   
1040           NaN  28/03/2018     2200         45          365       4090   
1041       17300.0  26/04/2018     2200         45          365       4051   
1042       16300.0  25/10/2016     1000         45          365       1930   
1043       17300.0  15/05/2019     2200         45          365       4451   

        AmtPaid60  AmtPaid360        LoanStatus  
LoanID                                           
1            4166       14621            Active  
2            4096       16041            Active  
3            3205       16340               NaN  
4            4166       16321            Active  
5            4745       14720            Active  
...           ...         ...               ...  
1039         4743       16617  Finished Payment  
1040         5582       16617  Finished Payment  
1041         5143       16617  Finished Payment  
1042         3462       15617  Finished Payment  
1043         4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [64]:
data = {'products':['Product A','Product B','Product C'],'price':[12121,212232,12323]}
ProductIDs = ['A','B','C']

In [78]:
df = pd.DataFrame(data,index=ProductIDs)
df

products   price
A  Product A   12121
B  Product B  212232
C  Product C   12323

## Using Numpy for importing csv files

In [79]:
import numpy as np

## Using np.loadtxt method to load the text file data CSV

In [90]:

numpy_file = np.loadtxt("Lending-Company-Numeric-Data.csv",delimiter=",")
numpy_file

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [91]:
type(numpy_file)

numpy.ndarray

## Using np.genfromtxt to load the text file data CSV

In [88]:
numpy_file_gen_csv = np.genfromtxt("Lending-Company-Numeric-Data.csv",delimiter=",")
numpy_file_gen_csv

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [87]:
type(numpy_file_gen_csv)

numpy.ndarray

In [95]:
#csv_semicolon = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=";")
csv_semicolon = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=";")
csv_semicolon

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [99]:
numpy_file[0,2] == numpy_file_gen_csv[0,2]

True

In [101]:
print(numpy_file[0,1])
print(numpy_file_gen_csv[0,1])

40.0
40.0


In [103]:
csv_semicolon = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=";",dtype=np.str)

C:\Users\basit\AppData\Local\Temp\ipykernel_26540\915213889.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  csv_semicolon = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",delimiter=";",dtype=np.str)
