# Importing Modules Practice

In [10]:
import math as m

In [5]:
m.sqrt(25)

5.0

In [6]:
sqrt(81)

9.0

In [3]:
from math import sqrt

In [4]:
sqrt(100)

10.0

In [7]:
from math import *

help(sqrt)

In [9]:
sqrt(99)

9.9498743710662

<hr style="border:5px solid #108999"> </hr>


# Mathematics for data analysis

<hr style="border:5px solid #108999"> </hr>


In [14]:
import numpy as np

In [16]:
arr1 = np.array([1,2,3,5])
arr1

array([1, 2, 3, 5])

In [17]:
arr2 = np.ndarray([1,2,3,5])

In [18]:
arr2

array([[[[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000]],

        [[-3.26065105e-311,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000]]]])

In [21]:
type(arr1)

numpy.ndarray

In [20]:
print(type(arr1))

<class 'numpy.ndarray'>


<b>Scalars:

In [23]:
s = 65
s

65

<b>Vectors:

In [25]:
v = np.array([12,65,121])
v

array([ 12,  65, 121])

<b> Matrices

In [29]:
m = np.array([[12,42,13,15],[6,23,11,23]])
m

array([[12, 42, 13, 15],
       [ 6, 23, 11, 23]])

<b>#Data type

In [31]:
type(s)

int

In [32]:
type(v)

numpy.ndarray

In [33]:
type(m)

numpy.ndarray

In [35]:
s_array = np.array([5])
s_array

array([5])

In [36]:
type(s_array)

numpy.ndarray

<b>Data Shapes

In [38]:
m.shape

(2, 4)

In [39]:
v.shape

(3,)

In [41]:
s_array.shape

(1,)

<b>Creating a Column Vector

In [45]:
v.reshape(1,3)

array([[ 12,  65, 121]])

In [46]:
print(v)

[ 12  65 121]


In [47]:
v.reshape(3,1)

array([[ 12],
       [ 65],
       [121]])

In [48]:
print(v)

[ 12  65 121]


In [49]:
m

array([[12, 42, 13, 15],
       [ 6, 23, 11, 23]])

In [50]:
m+s

array([[ 77, 107,  78,  80],
       [ 71,  88,  76,  88]])

In [51]:
s

65

In [52]:
m + s_array

array([[17, 47, 18, 20],
       [11, 28, 16, 28]])

In [53]:
s_array

array([5])

In [54]:
v+s

array([ 77, 130, 186])

In [57]:
v

array([ 12,  65, 121])